### ISSUE TITLE
Support for Crystal 1.0.0

### ISSUE THREAD

**Issue by gabojkz** [spider-gazelle/spider-gazelle#11]
There is not support for crystal 1.0.0 I think

This is the error:

Unable to satisfy the following requirements:

- `crystal (< 1.0.0)` required by `action-controller 3.5.2`
- `crystal (>= 1.0.0)` required by `active-model 2.0.4`
- `crystal (>= 0.36.1)` required by `secrets-env 1.3.1`
- `crystal (< 1.0.0)` required by `kilt 0.6.0`
- `crystal (>= 0.35.0)` required by `ameba 0.14.1`
- `crystal (~> 0.34, >= 0.34.0)` required by `future 0.1.0`
- `crystal (~> 0.36, >= 0.36.1)` required by `habitat 0.4.6`
- `crystal (~> 0.36, >= 0.36.1)` required by `lucky_router 0.4.1`
Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.

**Comment by stakach** [comment]
@gabojkz no issues running on crystal 1.0.0
we've already updated most of our production services to crystal 1.0.0 already

The shards issue is caused by `active-model` requiring some old shards that were pulled out of the standard library
* https://github.com/crystal-lang/json_mapping.cr
* https://github.com/crystal-lang/yaml_mapping.cr

we have the following pull request in progress to resolve this: https://github.com/spider-gazelle/active-model/pull/28

You probably won't need active-model in your project unless you're using rethinkdb

**Comment by gabojkz** [comment]
You can close this: shards --ignore-crystal-version, it worked for me.

@stakach Thanks
